-- Este arquivo foi substituído por supabase/migrations/ — rode os arquivos
-- dessa pasta em ordem numérica (0001, 0002, ...) contra o projeto Supabase
-- real. Mantendo um único lugar como fonte de verdade do schema, para não
-- haver duas versões divergentes do mesmo banco.
--
-- Ver supabase/migrations/0001_initial_schema.sql e
-- supabase/migrations/0002_copilot_insights.sql.
